version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GITHUB_API_KEY=${GITHUB_API_KEY}
      - HUGGING_FACE_API_KEY=${HUGGING_FACE_API_KEY}
    env_file:
      - backend/.env.example
