from app.constants import *

VALID_TRANSITIONS = {
    ORDER_STATE_NEW: {ORDER_STATE_ACK, ORDER_STATE_REJECTED, ORDER_STATE_CANCELLED},
    ORDER_STATE_ACK: {ORDER_STATE_OPEN, ORDER_STATE_PARTIAL, ORDER_STATE_FILLED, ORDER_STATE_CANCELLED, ORDER_STATE_REJECTED},
    ORDER_STATE_OPEN: {ORDER_STATE_PARTIAL, ORDER_STATE_FILLED, ORDER_STATE_CANCELLED},
    ORDER_STATE_PARTIAL: {ORDER_STATE_PARTIAL, ORDER_STATE_FILLED, ORDER_STATE_CANCELLED},
}

def can_transition(old: str, new: str) -> bool:
    return new == old or new in VALID_TRANSITIONS.get(old, set())
