use serde::{Deserialize, Serialize};
use sha3::{Digest, Keccak256};
use std::sync::Arc;
use tokio::sync::RwLock;
use chrono::Utc;
use uuid::Uuid;

/// Every prompt from a human IS a transaction.
/// Every token generated by LLM IS a micro-transaction earning money.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Transaction {
    pub tx_hash: String,
    pub from: String,
    pub to: String,
    pub amount: u64,
    pub tx_type: TxType,
    pub data: TxData,
    pub timestamp: i64,
    pub nonce: u64,
    pub inference_hash: String,
    pub signature: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TxType {
    Prompt,        // Human writes prompt → costs small fee
    Inference,     // LLM generates token → earns money
    Response,      // Complete response delivered → settlement
    ConsensusVote, // LLM validates batch → earns validator fee
    CrossChain,    // Settlement to Solana/Sui/Bera
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TxData {
    pub prompt: Option<String>,
    pub response: Option<String>,
    pub token_count: u64,
    pub model: String,
    pub proof_hash: String,
}

impl Transaction {
    pub fn new_prompt(from: &str, prompt_text: &str, model: &str) -> Self {
        let timestamp = Utc::now().timestamp_millis();
        let inference_hash = Self::hash_prompt(prompt_text, timestamp);
        let tx_hash = Self::compute_hash(from, "network", 1, &inference_hash, timestamp);
        
        Self {
            tx_hash,
            from: from.to_string(),
            to: "network".to_string(),
            amount: 1, // 1 lamport base fee
            tx_type: TxType::Prompt,
            data: TxData {
                prompt: Some(prompt_text.to_string()),
                response: None,
                token_count: 0,
                model: model.to_string(),
                proof_hash: inference_hash.clone(),
            },
            timestamp,
            nonce: 0,
            inference_hash: inference_hash.clone(),
            signature: inference_hash,
        }
    }
    
    pub fn new_inference(parent_tx: &str, token: &str, model: &str, token_index: u64) -> Self {
        let timestamp = Utc::now().timestamp_millis();
        let proof_hash = Self::hash_token(parent_tx, token, timestamp);
        let tx_hash = Self::compute_hash("network", "validator", 1, &proof_hash, timestamp);
        
        Self {
            tx_hash,
            from: "network".to_string(),
            to: "validator".to_string(),
            amount: 100, // Each token earns 100 base units
            tx_type: TxType::Inference,
            data: TxData {
                prompt: None,
                response: Some(token.to_string()),
                token_count: 1,
                model: model.to_string(),
                proof_hash: proof_hash.clone(),
            },
            timestamp,
            nonce: token_index,
            inference_hash: parent_tx.to_string(),
            signature: proof_hash,
        }
    }
    
    fn hash_prompt(prompt: &str, ts: i64) -> String {
        let mut hasher = Keccak256::new();
        hasher.update(prompt.as_bytes());
        hasher.update(ts.to_string().as_bytes());
        hex::encode(hasher.finalize())
    }
    
    fn hash_token(parent: &str, token: &str, ts: i64) -> String {
        let mut hasher = Keccak256::new();
        hasher.update(parent.as_bytes());
        hasher.update(token.as_bytes());
        hasher.update(ts.to_string().as_bytes());
        hex::encode(hasher.finalize())
    }
    
    fn compute_hash(from: &str, to: &str, amount: u64, data_hash: &str, ts: i64) -> String {
        let mut hasher = Keccak256::new();
        hasher.update(from.as_bytes());
        hasher.update(to.as_bytes());
        hasher.update(amount.to_string().as_bytes());
        hasher.update(data_hash.as_bytes());
        hasher.update(ts.to_string().as_bytes());
        hex::encode(hasher.finalize())
    }
}

/// High-throughput transaction pool — 1M+ TPS capacity
pub struct TransactionPool {
    pending: Arc<RwLock<Vec<Transaction>>>,
    processed: Arc<RwLock<u64>>,
}

impl TransactionPool {
    pub fn new() -> Self {
        Self {
            pending: Arc::new(RwLock::new(Vec::with_capacity(100000))),
            processed: Arc::new(RwLock::new(0)),
        }
    }
    
    pub async fn submit(&self, tx: Transaction) {
        let mut pool = self.pending.write().await;
        pool.push(tx);
    }
    
    pub async fn drain_batch(&self, size: usize) -> Vec<Transaction> {
        let mut pool = self.pending.write().await;
        let drain_count = size.min(pool.len());
        let batch: Vec<Transaction> = pool.drain(0..drain_count).collect();
        
        let mut processed = self.processed.write().await;
        *processed += batch.len() as u64;
        
        batch
    }
    
    pub async fn len(&self) -> usize {
        let pool = self.pending.read().await;
        pool.len()
    }
    
    pub async fn processed_count(&self) -> u64 {
        let p = self.processed.read().await;
        *p
    }
}
