import asyncio
import time
import json
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from app.core.config import settings
from app.core.logging import get_logger
from app.models.schemas import AgentCapability, AgentMetadata, AgentRequest, AgentResult
from app.services.llm_service import llm_service
from app.services.stripe_service import stripe_service
from app.services.twilio_service import twilio_service
from app.services.email_service import email_service
from app.services.vercel_service import vercel_service
from app.services.github_service import github_service

logger = get_logger("agent_base")

class AgentWorker(ABC):
    id: str = "base"
    name: str = "Base Agent"
    description: str = "Base agent implementation"
    category: str = "base"
    version: str = "1.0.0"
    price_per_run: int = 100  # cents
    model: str = "gpt-4o"
    supported_llms: List[str] = ["gpt-4o", "gpt-4o-mini", "claude-3-5-sonnet-20240620", "llama3-70b-8192"]
    capabilities: List[AgentCapability] = []
    tags: List[str] = []

    def __init__(self):
        self.logger = get_logger(f"agent.{self.id}")
        self._setup_capabilities()

    def _setup_capabilities(self):
        if not self.capabilities:
            self.capabilities = [
                AgentCapability(name="llm_generate", description="Generate text via LLM"),
                AgentCapability(name="deploy", description="Create repo and deploy to Vercel"),
                AgentCapability(name="notify", description="Send email and SMS notifications"),
            ]

    @property
    def metadata(self) -> AgentMetadata:
        return AgentMetadata(
            id=self.id,
            name=self.name,
            description=self.description,
            category=self.category,
            version=self.version,
            capabilities=self.capabilities,
            price_per_run=self.price_per_run,
            model=self.model,
            supported_llms=self.supported_llms,
            endpoints=[f"/agents/{self.id}/run", f"/agents/{self.id}/info"],
            tags=self.tags,
            author="AgentWorkforce",
        )

    @abstractmethod
    async def _run(self, request: AgentRequest) -> Any:
        """Override in subclass."""
        pass

    async def run(self, request: AgentRequest) -> AgentResult:
        start = time.time()
        self.logger.info("agent_run_start", agent_id=self.id, query=request.query[:100])
        try:
            output = await self._run(request)
            result = AgentResult(
                agent_id=self.id,
                status="success",
                output=output,
                execution_time_ms=(time.time() - start) * 1000,
                metadata={"model": self.model},
            )
            await self._post_run(request, result)
            self.logger.info("agent_run_success", agent_id=self.id, elapsed_ms=result.execution_time_ms)
            return result
        except Exception as e:
            self.logger.error("agent_run_failed", agent_id=self.id, error=str(e))
            return AgentResult(
                agent_id=self.id,
                status="error",
                output={"error": str(e)},
                execution_time_ms=(time.time() - start) * 1000,
                metadata={"error_type": type(e).__name__},
            )

    async def _post_run(self, request: AgentRequest, result: AgentResult):
        # Send notifications
        if request.notify_email:
            summary = json.dumps(result.output, default=str)[:500]
            await email_service.send_agent_result(request.notify_email, self.id, summary)
        if request.notify_sms:
            from app.models.schemas import TwilioNotificationRequest
            await twilio_service.send_sms(TwilioNotificationRequest(
                to=request.notify_sms,
                message=f"Agent {self.id} completed. Status: {result.status}",
                agent_id=self.id,
            ))
        # Create repo and deploy if requested
        if request.create_repo and request.repo_name:
            files = self._generate_repo_files(result)
            repo = await github_service.create_repo_and_push(
                repo_name=request.repo_name,
                files=files,
                private=False,
                description=f"Auto-generated by {self.name}",
            )
            result.repo_url = repo.repo_url
            if request.deploy_to_vercel:
                deploy = await vercel_service.deploy_repo(
                    repo_url=repo.repo_url,
                    project_name=request.repo_name,
                )
                result.deployment_url = deploy.deployment_url

    def _generate_repo_files(self, result: AgentResult) -> Dict[str, str]:
        """Override in subclasses to generate deployable files."""
        return {
            "README.md": f"# {self.name}\n\nAuto-generated by AgentWorkforce.\n\n## Output\n\n```json\n{json.dumps(result.output, default=str, indent=2)[:2000]}\n```",
            "index.html": f"<!DOCTYPE html><html><head><title>{self.name}</title></head><body><h1>{self.name}</h1><pre>{json.dumps(result.output, default=str, indent=2)[:5000]}</pre></body></html>",
        }

    async def _llm(self, prompt: str, system: Optional[str] = None, json_mode: bool = False, max_tokens: int = 2048) -> Dict[str, Any]:
        return await llm_service.generate(prompt, model=self.model, system=system, json_mode=json_mode, max_tokens=max_tokens)

    async def _web_fetch(self, url: str) -> str:
        import httpx
        async with httpx.AsyncClient(timeout=30.0) as client:
            try:
                r = await client.get(url, headers={"User-Agent": "AgentWorkforce/1.0"})
                return r.text[:8000]
            except Exception as e:
                return f"Error fetching {url}: {e}"

    async def _stripe_charge(self, customer_id: str, usage_units: int):
        return await stripe_service.process_usage_billing(self.id, customer_id, usage_units, unit_price_cents=self.price_per_run)
